export const INIT_USER = "INIT_USER";
export const INIT_OTHER_USER = "INIT_OTHER_USER";

export const LOAD_SELF_USER = "LOAD_SELF_USER";
export const SELF_USER_LOADED = "SELF_USER_LOADED";
export const LOAD_OTHER_USER = "LOAD_OTHER_USER";
export const OTHER_USER_LOADED = "OTHER_USER_LOADED";
export const ADD_USER_FOLLOWING_DATA = "ADD_USER_FOLLOWING_DATA";
export const ADD_FOLLOWING_DATA_OTHER = "ADD_FOLLOWING_DATA_OTHER";

export const RESET = "RESET"

// export const UPDATE_NAME = "UPDATE_NAME";
// export const UPDATE_BIO = "UPDATE_BIO";
// export const UPDATE_PERSONAL_DETAILS = "UPDATE_PERSONAL_DETAILS";
export const UPDATE_USER = "UPDATE_USER";
export const FOLLOW_USER = "FOLLOW_USER";
export const UNFOLLOW_USER = "UNFOLLOW_USER";

// ERROR ACTIONS
export const ADD_ERROR = "ADD_ERROR";
export const REMOVE_ERROR = "REMOVE_ERROR";

// POST ACTIONS
export const GET_POSTS_BY_USERNAME = "GET_POSTS_BY_USERNAME";
export const ADD_LIKE = "ADD_LIKE";
export const REMOVE_LIKE = "REMOVE_LIKE";
export const ADD_COMMENT = "ADD_COMMENT";
export const GET_ALL_COMMENTS = "GET_ALL_COMMENTS";

// NEWS FEED ACTIONS
export const INIT__FEED = "INIT__FEED";
export const ADD_OWN_POST = "ADD_OWN_POST"

// CHAT
export const ADD_MESSAGE = "ADD_MESSAGE";
export const ADD_RECIEVED_MESSAGE = "ADD_RECIEVED_MESSAGE";
export const LOAD_MESSAGES = "LOAD_MESSAGES";
export const CONVO_LIST_LOADED = "CONVO_LIST_LOADED";
export const CONVO_LIST_NOT_LOADED = "CONVO_LIST_NOT_LOADED";
export const LOAD_CONVO_LIST = "LOAD_CONVO_LIST";
export const SET_MINIMISED = "SET_MINIMISED";
export const INIT_CONVERSATION = "INIT_CONVERSATION";
export const SET_CURRENT_CHAT = "SET_CURRENT_CHAT"