
name: Heroku-Deploy
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.5.6
        with:
          heroku_api_key: ${{secrets.heroku_key}}
          heroku_app_name: "campus-social-media"
          heroku_email: "satvik.dandale17@vit.edu"

      - name: Run a one-line script
        run: echo Hello, world!
